server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Vue SPA — redireciona rotas para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API → PHP-FPM (FastCGI)
    location /api {
        fastcgi_pass backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param SCRIPT_NAME     /index.php;
        fastcgi_param DOCUMENT_ROOT   /var/www/html/public;
        fastcgi_param REQUEST_URI     $request_uri;
        fastcgi_param SERVER_NAME     $host;
        fastcgi_read_timeout 300;
    }
}
