name: CI/CD para AKS com Azure Container Registry

on:
  push:
    branches:
      - master
      - desenvolvimento

env:
  REGISTRY: suppregistry.azurecr.io
  BACKEND_IMAGE_NAME: helpdesk/supp-backend-kubernetes
  WEBSERVER_IMAGE_NAME: helpdesk/supp-webserver-kubernetes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Definir variáveis de ambiente
        run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Login no Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build e Push da imagem Backend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f ./docker/php/Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Build e Push da imagem Webserver
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.WEBSERVER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f ./docker/nginx/Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ env.WEBSERVER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Configurar acesso ao Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Substituir IMAGE_TAG nos arquivos YAML
        run: |
          find kubernetes/ -type f -name "*.yaml" -exec sed -i "s|IMAGE_TAG|${{ env.IMAGE_TAG }}|g" {} +

      - name: Aplicar deployments no AKS
        run: |
          kubectl apply -f kubernetes/backend-deployment.yaml -n helpdesk
          kubectl apply -f kubernetes/backend-service.yaml -n helpdesk
          kubectl apply -f kubernetes/webserver-deployment.yaml -n helpdesk
          kubectl apply -f kubernetes/webserver-service.yaml -n helpdesk
          kubectl apply -f kubernetes/ingress.yaml -n helpdesk
